
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xe5\x14ZQ\xc0]0\xc0=\xd5\x90\xe8\xc7\xc0r\xd7'
    
_lr_action_items = {'TYPE_1PARAM':([12,],[21,]),'TIMEZONE_PARAM':([67,],[79,]),'NUMBER':([28,33,34,35,46,52,57,69,],[41,48,49,50,62,70,73,80,]),'EOL':([13,23,24,26,36,37,40,44,45,51,55,56,58,59,60,66,68,74,77,81,82,85,86,],[26,-37,-13,40,26,-18,40,-37,-25,-17,26,26,-24,-37,26,26,-14,-23,26,-19,-26,-16,-15,]),'LBRACKET':([23,24,36,37,51,68,81,85,86,],[-37,-13,52,-18,-17,-14,-19,-16,-15,]),'PATH':([46,],[63,]),'FILL_METHOD_NOPARAM':([19,],[32,]),'RPAREN':([41,42,47,49,61,62,63,64,65,73,79,80,83,],[55,56,66,68,-30,-31,-29,-32,77,82,85,86,-33,]),'CONSTRAINT':([18,26,38,39,40,54,78,84,],[30,-37,-34,-36,-37,-35,-20,-21,]),'FILL_METHOD_1PARAM':([19,],[31,]),'DOUBLE_COLON':([1,7,14,15,18,26,27,29,38,39,40,54,71,72,75,78,84,],[6,-37,-6,6,-9,-37,-5,-10,-34,-36,-37,-35,-7,-8,-22,-20,-21,]),'COLON':([4,64,],[10,76,]),'TABLE':([0,2,7,8,9,14,15,16,18,26,27,29,38,39,40,54,75,78,84,],[4,-37,-37,-3,4,-6,-4,-2,-9,-37,-5,-10,-34,-36,-37,-35,-22,-20,-21,]),'FILL':([11,26,38,39,40,53,54,],[19,-37,-34,-36,-37,-12,-35,]),'FILLED':([28,],[42,]),'$end':([2,3,7,8,9,14,15,16,18,26,27,29,38,39,40,54,75,78,84,],[-37,0,-37,-3,-1,-6,-4,-2,-9,-37,-5,-10,-34,-36,-37,-35,-22,-20,-21,]),'REGEX':([46,],[61,]),'TYPE_2PARAM_TIME':([12,],[20,]),'CONSTR_1PARAM':([30,44,45,59,82,],[43,43,-25,43,-26,]),'TYPE_NOPARAM':([12,],[24,]),'LPAREN':([17,20,21,22,31,32,43,],[28,33,34,35,46,47,57,]),'IDENTIFIER':([6,10,46,76,],[13,17,64,83,]),'TYPE_2PARAM':([12,],[22,]),'RBRACKET':([70,],[81,]),'COMMA':([48,50,],[67,69,]),'TYPE':([5,25,26,38,39,40,54,],[12,-11,-37,-34,-36,-37,-35,]),'CONSTR_NOPARAM':([30,44,45,59,82,],[45,45,-25,45,-26,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'tableHeader':([0,9,],[1,1,]),'constraintPart':([18,],[29,]),'fillMethod':([11,],[18,]),'oneDimension':([36,],[51,]),'tableBlock':([0,9,],[2,16,]),'moreAttributes':([7,],[15,]),'dataType':([5,],[11,]),'attributeName':([1,15,],[5,5,]),'moreBlocks':([2,],[9,]),'dtypes':([12,],[23,]),'dsl':([0,],[3,]),'attributeBlock':([1,15,],[7,27,]),'constr':([30,44,59,],[44,59,59,]),'moreConstr':([44,59,],[60,74,]),'endline':([13,36,55,56,60,66,77,],[25,53,71,72,75,78,84,]),'parameter':([46,],[65,]),'moreDimensions':([23,],[36,]),'empty':([2,7,23,26,40,44,59,],[8,14,37,39,39,58,58,]),'extraEndline':([26,40,],[38,54,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> dsl","S'",1,None,None,None),
  ('dsl -> tableBlock moreBlocks','dsl',2,'p_dsl','/home/re/sql-data-farmer/Seeder/lex_parse.py',315),
  ('moreBlocks -> moreBlocks tableBlock','moreBlocks',2,'p_moreBlocks','/home/re/sql-data-farmer/Seeder/lex_parse.py',320),
  ('moreBlocks -> empty','moreBlocks',1,'p_moreBlocks','/home/re/sql-data-farmer/Seeder/lex_parse.py',321),
  ('tableBlock -> tableHeader attributeBlock moreAttributes','tableBlock',3,'p_tableBlock','/home/re/sql-data-farmer/Seeder/lex_parse.py',331),
  ('moreAttributes -> moreAttributes attributeBlock','moreAttributes',2,'p_moreAttributes','/home/re/sql-data-farmer/Seeder/lex_parse.py',336),
  ('moreAttributes -> empty','moreAttributes',1,'p_moreAttributes','/home/re/sql-data-farmer/Seeder/lex_parse.py',337),
  ('tableHeader -> TABLE COLON IDENTIFIER LPAREN NUMBER RPAREN endline','tableHeader',7,'p_tableHeader','/home/re/sql-data-farmer/Seeder/lex_parse.py',342),
  ('tableHeader -> TABLE COLON IDENTIFIER LPAREN FILLED RPAREN endline','tableHeader',7,'p_tableHeader','/home/re/sql-data-farmer/Seeder/lex_parse.py',343),
  ('attributeBlock -> attributeName dataType fillMethod','attributeBlock',3,'p_attributeBlock','/home/re/sql-data-farmer/Seeder/lex_parse.py',356),
  ('attributeBlock -> attributeName dataType fillMethod constraintPart','attributeBlock',4,'p_attributeBlock','/home/re/sql-data-farmer/Seeder/lex_parse.py',357),
  ('attributeName -> DOUBLE_COLON IDENTIFIER endline','attributeName',3,'p_attributeName','/home/re/sql-data-farmer/Seeder/lex_parse.py',375),
  ('dataType -> TYPE dtypes moreDimensions endline','dataType',4,'p_dataType','/home/re/sql-data-farmer/Seeder/lex_parse.py',385),
  ('dtypes -> TYPE_NOPARAM','dtypes',1,'p_dtypes','/home/re/sql-data-farmer/Seeder/lex_parse.py',390),
  ('dtypes -> TYPE_1PARAM LPAREN NUMBER RPAREN','dtypes',4,'p_dtypes','/home/re/sql-data-farmer/Seeder/lex_parse.py',391),
  ('dtypes -> TYPE_2PARAM LPAREN NUMBER COMMA NUMBER RPAREN','dtypes',6,'p_dtypes','/home/re/sql-data-farmer/Seeder/lex_parse.py',392),
  ('dtypes -> TYPE_2PARAM_TIME LPAREN NUMBER COMMA TIMEZONE_PARAM RPAREN','dtypes',6,'p_dtypes','/home/re/sql-data-farmer/Seeder/lex_parse.py',393),
  ('moreDimensions -> moreDimensions oneDimension','moreDimensions',2,'p_moreDimensions','/home/re/sql-data-farmer/Seeder/lex_parse.py',419),
  ('moreDimensions -> empty','moreDimensions',1,'p_moreDimensions','/home/re/sql-data-farmer/Seeder/lex_parse.py',420),
  ('oneDimension -> LBRACKET NUMBER RBRACKET','oneDimension',3,'p_oneDimension','/home/re/sql-data-farmer/Seeder/lex_parse.py',424),
  ('fillMethod -> FILL FILL_METHOD_NOPARAM LPAREN RPAREN endline','fillMethod',5,'p_fillMethod','/home/re/sql-data-farmer/Seeder/lex_parse.py',434),
  ('fillMethod -> FILL FILL_METHOD_1PARAM LPAREN parameter RPAREN endline','fillMethod',6,'p_fillMethod','/home/re/sql-data-farmer/Seeder/lex_parse.py',435),
  ('constraintPart -> CONSTRAINT constr moreConstr endline','constraintPart',4,'p_constraintPart','/home/re/sql-data-farmer/Seeder/lex_parse.py',448),
  ('moreConstr -> constr moreConstr','moreConstr',2,'p_moreConstr','/home/re/sql-data-farmer/Seeder/lex_parse.py',452),
  ('moreConstr -> empty','moreConstr',1,'p_moreConstr','/home/re/sql-data-farmer/Seeder/lex_parse.py',453),
  ('constr -> CONSTR_NOPARAM','constr',1,'p_constr','/home/re/sql-data-farmer/Seeder/lex_parse.py',457),
  ('constr -> CONSTR_1PARAM LPAREN NUMBER RPAREN','constr',4,'p_constr','/home/re/sql-data-farmer/Seeder/lex_parse.py',458),
  ('parameters -> parameters parameter','parameters',2,'p_parameters','/home/re/sql-data-farmer/Seeder/lex_parse.py',506),
  ('parameters -> empty','parameters',1,'p_parameters','/home/re/sql-data-farmer/Seeder/lex_parse.py',507),
  ('parameter -> PATH','parameter',1,'p_parameter','/home/re/sql-data-farmer/Seeder/lex_parse.py',511),
  ('parameter -> REGEX','parameter',1,'p_parameter','/home/re/sql-data-farmer/Seeder/lex_parse.py',512),
  ('parameter -> NUMBER','parameter',1,'p_parameter','/home/re/sql-data-farmer/Seeder/lex_parse.py',513),
  ('parameter -> IDENTIFIER','parameter',1,'p_parameter','/home/re/sql-data-farmer/Seeder/lex_parse.py',514),
  ('parameter -> IDENTIFIER COLON IDENTIFIER','parameter',3,'p_parameter','/home/re/sql-data-farmer/Seeder/lex_parse.py',515),
  ('endline -> EOL extraEndline','endline',2,'p_endline','/home/re/sql-data-farmer/Seeder/lex_parse.py',524),
  ('extraEndline -> EOL extraEndline','extraEndline',2,'p_extraEndline','/home/re/sql-data-farmer/Seeder/lex_parse.py',528),
  ('extraEndline -> empty','extraEndline',1,'p_extraEndline','/home/re/sql-data-farmer/Seeder/lex_parse.py',529),
  ('empty -> <empty>','empty',0,'p_empty','/home/re/sql-data-farmer/Seeder/lex_parse.py',534),
]
